[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.12.0"

[[plugins]]
  package = "netlify-plugin-playwright-cache"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
